Improve spurious wakeup handling in USB transfer waiting
myriadrf/LimeSuite pull request #321
Opened 2020-10-24 13:56 UTC by Gluttton

The current implementation tries to handle spurious wakeups manually,
but the standard library provides the overloaded version of the
`std::condition_variable::wait_for` that can be used to ignore spurious
awakenings.

Also, the current implementation has a minor logical error: in the case of
false wakeup, the next sleep timeout should be reduced by the time that
was spent on previous waiting.

For details see:
 - https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for ;
 - https://en.cppreference.com/w/cpp/thread/condition_variable/wait .

2020-10-28 15:32 UTC, gracid requested changes
Hello, thanks for the pull request. 
I have requested some minor changes to keep the functionality the same. Also, this change only affects boards which use FX3 connections, same could be done for FTDI, to keep it consistent for USB handling.

2020-10-28 15:32 UTC, gracid commented on src/ConnectionFX3/ConnectionFX3.cpp
> +    return contexts[contextHandle].done == true;
On a timeout, while unlikely, contexts[contextHandle].done value could have changed, since you are not loading it anymore.

2020-10-28 15:32 UTC, gracid commented on src/ConnectionFX3/ConnectionFX3.cpp
> +    return contextsToSend[contextHandle].done == true;
On a timeout, while unlikely, contextsToSend[contextHandle].done value could have changed, since you are not loading it anymore.

2020-10-28 20:17 UTC, Gluttton commented
Hello @gracid,
Thank you for your feedback.

> since you are not loading it anymore.

In general, I agree with the requests, but I almost sure that the current implementation does the same. Both `std::atomic<T>::load` and `std::atomic<T>::operator T` acquire a value of an atomic variable. According to the [documentation](https://en.cppreference.com/w/cpp/atomic/atomic/operator_T) they are equivalent:

> `std::atomic<T>::operator T`
> 
> Atomically loads and returns the current value of the atomic variable. Equivalent to `load()`. 

To resolve the requests I was going to add an explicit call of `load` in all `done` reading:
```suggestion
    return contexts[contextHandle].done.load() == true;
```

But then I revised [documentation](https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for) for `std::condition_variable::wait_for` and paid attention that this function has a return value, that already indicates whether a predicate satisfied or not:

> Return value
> 2) `false` if the predicate **pred** still evaluates to `false` after the **rel_time** timeout expired, otherwise `true`.

So it seems like the second check of the `done` variable is redundant at all, and can be omitted.

> same could be done for FTDI

Thanks for pointing this out! I've added changes for FTDI too.

I've uploaded the patch with these changes. I've tested (only FX3) it on my environment (Linux, LimeSDR USB) and it works well.
Could you please, check it and provide me with your feedback?

2020-10-29 08:48 UTC, gracid commented
> Both `std::atomic<T>::load` and `std::atomic<T>::operator T` acquire a value of an atomic variable. According to the [documentation](https://en.cppreference.com/w/cpp/atomic/atomic/operator_T) they are equivalent:
> 
> > `std::atomic<T>::operator T`
> > Atomically loads and returns the current value of the atomic variable. Equivalent to `load()`.

Oh, that is correct and it was using default memory order for those operation anyways.

> Thanks for pointing this out! I've added changes for FTDI too.
> 
> I've uploaded the patch with these changes. I've tested (only FX3) it on my environment (Linux, LimeSDR USB) and it works well.
> Could you please, check it and provide me with your feedback?

Looks good, thanks.

2020-10-29 08:49 UTC, merged